### ISSUE TITLE
SessionNotCreatedException: Message: start video container: start video container: Error response from daemon: error while creating mount source path '/c/Users/admin/.aerokube/selenoid/video': mkdir /c: file exists

### ISSUE THREAD

**Issue by madb1ker** [aerokube/selenoid#1373]
Having this issue with Selenoid on Robot Framework running in Windows 10 Pro (works fine in Linux).

When enableVideo=True I get the following error:

SessionNotCreatedException: Message: start video container: start video container: Error response from daemon: error while creating mount source path '/c/Users/admin/.aerokube/selenoid/video': mkdir /c: file exists

Selenoid installed with latest cm.exe.

Using Docker.
![image](https://github.com/aerokube/selenoid/assets/79003568/cd9f8827-b52b-4c4f-860c-a33925ce8b56)

Without enableVideo=True everything works fine, but no video recorded of course.

Any sugestions?

**Comment by vania-pooh** [comment]
@madb1ker could be related to Docker volumes settings. Any experimental options enabled?

**Comment by madb1ker** [comment]
> @madb1ker could be related to Docker volumes settings. Any experimental options enabled?

No experimental options enabled.
Clean docker and Selenoid install through the latest CM.exe binary.

**Comment by kemielis3456** [comment]
I'm facing the same thing. No experimental options. Started Selenoid from CM.

**Comment by kemielis3456** [comment]
@madb1ker Can you let me know how did you install docker on your WSL Ubuntu instance? I cannot start the docker service.

**Comment by madb1ker** [comment]
> @madb1ker Can you let me know how did you install docker on your WSL Ubuntu instance? I cannot start the docker service.

You don't install Docker "in" the WSL Ubuntu. You install in Windows and enable integration with the distro.
![image](https://github.com/aerokube/selenoid/assets/79003568/b5697b9d-3d9d-41ee-9714-f2433a3bca20)

**Comment by kemielis3456** [comment]
@madb1ker Thank you, I managed to get video recording work now!

**Comment by vania-pooh** [comment]
So this is resolved, right?

**Comment by madb1ker** [comment]
> So this is resolved, right?

Not for me, I still cannot get video recording for Selenoid under native Windows.
The solution above has using Linux in a WSL2 environment.
